<a href="https://colab.research.google.com/github/lientzubob/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(1000000)
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
list1 = list(np.arange(1000000))

In [ ]:
%time for _ in range(10): arr = a * 2

CPU times: user 12.6 ms, sys: 4.94 ms, total: 17.5 ms
Wall time: 24 ms


In [ ]:
%time for _ in range(10): list2 = [x * 2 for x in list1]

CPU times: user 2.17 s, sys: 155 ms, total: 2.33 s
Wall time: 2.34 s


In [ ]:
data = np.random.randn(2, 3)
data

array([[-0.75309852,  0.48287039, -0.57136123],
       [ 1.46996552, -0.46668719,  0.38503874]])

In [ ]:
data * 10

array([[-7.53098517,  4.82870388, -5.7136123 ],
       [14.69965524, -4.66687187,  3.85038743]])

In [ ]:
data + data

array([[-1.50619703,  0.96574078, -1.14272246],
       [ 2.93993105, -0.93337437,  0.77007749]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

In [ ]:
data = [1,2,3,4,5]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [ ]:
data = [[1,2,3,4,5], [6,7,8,9,10]]
arr = np.array(data)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 5)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2,3,2))

array([[[5.03681013e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [ ]:
arr.astype(np.float64).dtype

dtype('float64')

In [ ]:
arr = np.array([1.1, 2.2, 3.3, 4.4])
arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

In [ ]:
arr = np.array(["1.1", "2.2", "3.3", "4.4"], dtype=np.string_)
arr.astype(float)

array([1.1, 2.2, 3.3, 4.4])

In [ ]:
arr = np.array([[
    [1,2,3],
    [4,5,6]
]])
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr * arr

array([[[ 1,  4,  9],
        [16, 25, 36]]])

In [ ]:
arr - arr

array([[[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
1 / arr

array([[[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]])

In [ ]:
arr ** 0.5

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]])

In [ ]:
arr2 = np.array([[
    [1,1,1],
    [14,15,16]
]])
arr2 > arr

array([[[False, False, False],
        [ True,  True,  True]]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:2]

array([1])

In [ ]:
arr[1:3] = [11]
arr

array([ 0, 11, 11,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
arr[1][2]

6

In [ ]:
arr[1,2]

6

In [ ]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr[:2, 1:] = 0
arr

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.random.rand(10, 4)
arr2

In [ ]:
arr2[arr1 > 5]